### ISSUE TITLE
Breadcrumbs are not wrapped in a container

### ISSUE THREAD

**Issue by nickcolley** [alphagov/collections#210]
On smaller viewports the breadcrumbs do not have the correct padding.

![screen shot 2017-01-04 at 10 44 28](https://cloud.githubusercontent.com/assets/2445413/21639942/c956cbee-d26a-11e6-836a-12c9c12465ce.png)

**Comment by tijmenb** [comment]
Closed per https://github.com/alphagov/collections/pull/213.
