### ISSUE TITLE
Root browse page content hidden when going from a large width viewport to small

### ISSUE THREAD

**Issue by NickColley** [alphagov/collections#211]
A bit of an edge case but I've noticed if you load the browse page then decrease the viewport width, the content is hidden.

This only happens on https://www.gov.uk/browse

![govuk-browse-page-landscape-to-portrait](https://cloud.githubusercontent.com/assets/2445413/21640084/65d89394-d26b-11e6-811c-058ee686beda.gif)

**Comment by fofr** [comment]
Breadcrumb alignment looks wrong too.

**Comment by nickcolley** [comment]
See https://github.com/alphagov/collections/issues/210

**Comment by sihugh** [comment]
Thanks @NickColley. Browse pages have been replaced, and the new version doesn't seem to have this issue.

**Comment by sihugh** [comment]
Closing as fixed
