### ISSUE TITLE
Convert tests from Minitest to RSpec

### ISSUE THREAD

**Issue by hannako** [alphagov/collections#2259]
## Issue
- We are currently implementing Pact tests between Collections and gds-api-adapters in order to [meet the criteria](https://github.com/alphagov/govuk-rfcs/blob/master/rfc-128-continuous-deployment.md#check-api-contract-tests-pass-ie-adapters-work-with-their-apis) for CD of collections. 
- The pact gem brings in RSpec [as a dependency](https://github.com/alphagov/collections/blob/e3bc50f10b62357499053cfb4e214c63207f1c34/Gemfile.lock#L246). This will mean Collections runs two test suites, Minitest and RSpec. 
- This is not necessarily bad, eg Smart Answers also has both suites. However in the case of collections it adds a little bit of complexity. Collections uses cucumber for its feature tests, and they fail without [patching](https://github.com/alphagov/collections/pull/2245/commits/7e046459ea7abfb624495234f54de7a088a69e40) the Minitest assertions methods.
- RSpec is the GDS testing frame work [of choice](https://gds-way.cloudapps.digital/manuals/programming-languages/ruby.html#conventional-tooling), so it is probably worth taking the plunge and converting to Minitest. 

### Regular tests

There is a [rake task](https://github.com/alphagov/collections/blob/e5b305b7e7b3eae0020eed90987ea0abc83bb33d/lib/tasks/converter.rake) that can be used to do some of the syntax conversion.
```
bundle exec rake convert:to_rspec\["test/components","spec/views/components"\]
```
#### Convert the following
- [x] test/components
- [x] test/controllers
- [x] test/integration
- [x] test/lib
- [x] test/models
- [x] test/models/schemas
- [x] test/models/topic
- [x] test/presenters
- [x] test/presenters/organisations
- [x] test/presenters/supergroups
- [x] test/services
- [x] test/services/search
- [x] test/services/supergroup_sections
- [x] test/unit 

#### Once all tests requiring a specific helper have been ported over to RSpec, move the helpers from `test/support` ==> `spec/support`
- [x] analytics_helper
- [x] coronavirus_helper
- [x] coronavirus_landing_page_steps
- [x] custom_assertions
- [x] dit_landing_page_helper
- [x] gds_api_rummager_test_helpers
- [x] helpers
- [x] organisation_feed_helpers
- [x] organisation_helper
- [x] organisations_helpers
- [x] rummager_helpers
- [x] services_and_information_helpers
- [x] supergroups_helpers
- [x] taxon_helpers
- [x] transition_landing_page_steps

#### Convert features/step_definitions
- [x] browsing_topics_steps
- [x] curated_list_steps
- [x] latest_changes_steps
- [x] viewing_browse_steps
- [x] viewing_services_and_information_steps

### Tidy up

- remove `Dir[Rails.root.join("test/support/**/*.rb")].sort.each { |f| require f }` from spec_helper.
- Remove test_helper

**Comment by alex-ju** [comment]
It looks like this is all done now, @hannako, what do you think?
