### ISSUE TITLE
Padding on 'taxon email link' is big on small screens.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/collections#594]
Noticed this on my phone

<img width="391" alt="screen shot 2018-03-27 at 15 31 47" src="https://user-images.githubusercontent.com/2445413/37974151-1679e9f0-31d4-11e8-8dd6-754f0f79fe4f.png">

**Comment by nickcolley** [comment]
Team already knows about this and are tracking it here: https://trello.com/c/q2jv5vWK/7-issue-email-link-on-mobile-could-be-improved

**Comment by tijmenb** [comment]
👍 if it's tracked on Trello let's close it here. Thanks @nickcolley!
